#!/usr/bin/env bash

zsh_files=( ~/.zshrc ~/.zshenv ~/.zprofile )
zsh_dirs=( ~/.zshrc.d ~/.zshrc.d/aliases ~/.zshrc.d/functions )

# Delete old symlinks
find "$HOME/.zshrc.d" -type f -o -type l -delete

for d in "${zsh_dirs[@]}"; do
  if [ -L "${d}" ]; then
    rm -rf "${d}"
  fi
  if [ ! -d "${d}" ]; then
    mkdir -p "${d}"
  fi
done

for f in "${zsh_files[@]}"; do
  if [ -L "${f}" ] || [ -f "${f}" ]; then
    rm -f "${f}"
  fi
done

# vim: ft=sh ts=2 sts=2 sw=2 sr et
